### ISSUE TITLE
Update website content

### ISSUE THREAD

**Issue by cpojer** [phacility/javelin#49]
Can we remove the mention of "Facebook" on the javelin website now that it has been fully transferred to phacility? We still get people asking us internally whether the site was hacked.

**Comment by epriestley** [comment]
I think I'm just going to nuke the site, Javelin is alive and well in Phabricator but I don't think there's any real interest in maintaining it as a standalone library. I don't know how it has fared inside Facebook, but I assume it's no longer used anywhere.

**Comment by cpojer** [comment]
Facebook has recently created a spiritual successor to Javelin called "React". It has worse event handling and focused on reinventing the best practices Javelin has established. You should give it a try!

**Comment by epriestley** [comment]
no thanks I hate Javascript

**Comment by keyanzhang** [comment]
@cpojer that's correct and I'm actively hacking that now

**Comment by epriestley** [comment]
javelinjs.com now redirects to phacility.com/phabricator/

I could imagine a future where it gets a web page of its own again after we start supporting third-party application development (after <https://secure.phabricator.com/T5447>), but that's probably a year or two away. I'll make sure to take 100% of the credit if that does happen to avoid this problem in the future.

**Comment by Daniel15** [comment]
> I don't know how it has fared inside Facebook, but I assume it's no longer used anywhere.

m-touch still uses it! :smile:
